clear all;  
data = textread('K:\trainImage\roc_features\features.txt');
feature_names= {'Har-mean';'Har-var'};
[rows,cols] = size(data);
predict=data(1,1:cols-1);
ground_truth=data(rows,1:cols-1);  
plot_roc(predict,ground_truth,'Har-mean', 1);
predict=data(2,1:cols-1);
plot_roc(predict,ground_truth,'Har-var', 2);
predict=data(3,1:cols-1);
plot_roc(predict,ground_truth,'CV', 3);
predict=data(4,1:cols-1);
plot_roc(predict,ground_truth,'Hist', 4);
predict=data(5,1:cols-1);
plot_roc(predict,ground_truth,'Hist-mean', 5);
predict=data(6,1:cols-1);
plot_roc(predict,ground_truth,'Hist-variance', 6);
predict=data(7,1:cols-1);
plot_roc(predict,ground_truth,'Hist-skewness', 7);
predict=data(8,1:cols-1);
plot_roc(predict,ground_truth,'Hist-kurtosis', 8);
predict=data(9,1:cols-1);
plot_roc(predict,ground_truth,'BDIP', 9);
predict=data(10,1:cols-1);
plot_roc(predict,ground_truth,'NMSID', 10);
predict=data(11,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-energy', 11);
predict=data(12,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-contrast', 12);
predict=data(13,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-uniformity', 13);
predict=data(14,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-idm', 14);
predict=data(15,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-im', 15);
predict=data(16,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-correlation', 16);
predict=data(17,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-entropy', 17);
predict=data(18,1:cols-1);
plot_roc(predict,ground_truth,'Glcm-brightness', 18);

